name: educational_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.2
  chewie: ^1.7.0
  cloud_firestore: ^4.9.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  file_picker: ^5.3.3
  firebase_auth: ^4.8.0
  firebase_auth_mocks: ^0.12.0
  firebase_core: ^2.15.1
  firebase_storage: ^11.2.6
  firebase_ui_auth: ^1.6.5
  flutter_bloc: ^8.1.3
  flutter_tindercard:
    git:
      url: https://github.com/NonymousMorlock/flutter_tindercard.git
  font_awesome_flutter: ^10.5.0
  file_icon:
    git:
      url: https://github.com/NonymousMorlock/file_icon
  get_it: ^7.6.0
  iconly: ^1.0.1
  image_picker: ^1.0.2
  intl: ^0.18.1
  lottie: ^2.6.0
  open_file: ^3.3.2
  path_provider: ^2.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  smooth_page_indicator: ^1.1.0
  swipe_to: ^1.0.2
  url_launcher: ^6.1.12
  uuid: ^3.0.6
  video_thumbnail: ^0.5.3
  youtube_metadata: ^1.0.1
  badges: ^3.1.2
  audioplayers: ^5.1.0
  flutter_link_previewer: ^3.2.2
  flutter_chat_types: ^3.6.2
  video_player: ^2.7.2
  step_progress_indicator: ^1.0.2

dev_dependencies:
  bloc_test: ^9.1.5
  fake_cloud_firestore: ^2.4.1+1
  firebase_storage_mocks: ^0.6.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  google_sign_in_mocks: ^0.3.0
  mocktail: ^1.0.0
  very_good_analysis: ^5.0.0+1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/vectors/
    - assets/images/
    - assets/lottie/
    - assets/icons/
    - assets/sounds/

  fonts:
    - family: Aeonik
      fonts:
        - asset: assets/fonts/aeonik/AeonikTRIAL-Bold.otf
          weight: 700
        - asset: assets/fonts/aeonik/AeonikTRIAL-BoldItalic.otf
          style: italic
          weight: 700
        - asset: assets/fonts/aeonik/AeonikTRIAL-Light.otf
          weight: 300
        - asset: assets/fonts/aeonik/AeonikTRIAL-LightItalic.otf
          style: italic
          weight: 300
        - asset: assets/fonts/aeonik/AeonikTRIAL-Regular.otf
          weight: 400
        - asset: assets/fonts/aeonik/AeonikTRIAL-RegularItalic.otf
          style: italic
          weight: 400
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
